# Generated by Django 5.2.8 on 2025-12-13 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_use', models.CharField(choices=[('commercial', 'Commercial'), ('residential', 'Residential'), ('industrial', 'Industrial')], max_length=20)),
                ('target_use', models.CharField(choices=[('commercial', 'Commercial'), ('residential', 'Residential'), ('industrial', 'Industrial')], max_length=20)),
                ('country', models.CharField(choices=[('england', 'England'), ('scotland', 'Scotland'), ('wales', 'Wales')], max_length=20)),
                ('county', models.CharField(max_length=64)),
                ('postcode_prefix', models.CharField(max_length=10)),
                ('funding_band', models.CharField(choices=[('10000_20000', '£10,000 - £20,000'), ('21000_30000', '£21,000 - £30,000'), ('31000_40000', '£31,000 - £40,000'), ('41000_50000', '£41,000 - £50,000'), ('51000_75000', '£51,000 - £75,000'), ('76000_100000', '£76,000 - £100,000'), ('100000_150000', '£100,000 - £150,000'), ('151000_250000', '£151,000 - £250,000')], max_length=20)),
                ('return_type', models.CharField(choices=[('equity_share', 'Equity Share'), ('financial_payback', 'Financial Payback')], max_length=30)),
                ('return_band', models.CharField(choices=[('2_4', '2% - 4%'), ('5_9', '5% - 9%'), ('10_14', '10% - 14%'), ('15_17_5', '15% - 17.5%')], max_length=20)),
                ('duration_days', models.PositiveIntegerField()),
                ('price_per_day_pence', models.PositiveIntegerField(default=199)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_from', models.DateTimeField(blank=True, null=True)),
                ('active_until', models.DateTimeField(blank=True, null=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, default='', max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
