# Generated by Django 5.2.8 on 2025-12-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_listing_expected_amount_pence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='project_name',
            field=models.CharField(blank=True, default='', help_text='Optional project name shown in dashboards and opportunities (e.g. Old Police Station).', max_length=120),
        ),
    ]
