# Generated by Django 5.2.8 on 2025-12-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_listing_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='country',
            field=models.CharField(blank=True, choices=[('england', 'England'), ('scotland', 'Scotland'), ('wales', 'Wales')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='county',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='funding_band',
            field=models.CharField(blank=True, choices=[('10000_20000', '£10,000 - £20,000'), ('21000_30000', '£21,000 - £30,000'), ('31000_40000', '£31,000 - £40,000'), ('41000_50000', '£41,000 - £50,000'), ('51000_75000', '£51,000 - £75,000'), ('76000_100000', '£76,000 - £100,000'), ('100000_150000', '£100,000 - £150,000'), ('151000_250000', '£151,000 - £250,000')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='postcode_prefix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='return_band',
            field=models.CharField(blank=True, choices=[('2_4', '2% - 4%'), ('5_9', '5% - 9%'), ('10_14', '10% - 14%'), ('15_17_5', '15% - 17.5%')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='return_type',
            field=models.CharField(blank=True, choices=[('equity_share', 'Equity Share'), ('financial_payback', 'Financial Payback')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='source_use',
            field=models.CharField(blank=True, choices=[('commercial', 'Commercial'), ('residential', 'Residential'), ('industrial', 'Industrial')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='target_use',
            field=models.CharField(blank=True, choices=[('commercial', 'Commercial'), ('residential', 'Residential'), ('industrial', 'Industrial')], max_length=20, null=True),
        ),
    ]
