# Generated by Django 5.2.8 on 2025-12-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_listing_country_alter_listing_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='project_duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='How long the underlying project is expected to run (days).', null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='How long the listing stays active to secure funding (days).', null=True),
        ),
    ]
