# Generated by Django 5.2.8 on 2025-12-18 17:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_listing_expected_amount_pence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_pence', models.PositiveIntegerField()),
                ('expected_return_pence', models.PositiveIntegerField(default=0)),
                ('expected_total_back_pence', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pledged', 'Pledged'), ('cancelled', 'Cancelled')], default='pledged', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='users.listing')),
            ],
            options={
                'indexes': [models.Index(fields=['listing', 'status'], name='investments_listing_cac3e9_idx'), models.Index(fields=['investor', 'status'], name='investments_investo_5c61c8_idx')],
            },
        ),
    ]
